# Generated by Django 4.1 on 2022-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('whatsapp', models.BooleanField(verbose_name='Есть Whatsapp')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('settlement', models.CharField(max_length=255, verbose_name='Населенный пункт')),
                ('category', models.CharField(choices=[('CAR', 'Car'), ('SPECIAL_CAR', 'Special Car'), ('PARTS', 'Parts'), ('MOTO_TECHNICS', 'Moto Technics'), ('BOATS', 'Boats')], default='CAR', max_length=128, verbose_name='Подкатегория авто')),
                ('action', models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy'), ('TRADE', 'Trade'), ('RENT_OUT', 'Rent Out'), ('TO_RENT', 'To Rent')], default='SELL', max_length=128, verbose_name='Действие авто')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('whatsapp', models.BooleanField(verbose_name='Есть Whatsapp')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('settlement', models.CharField(max_length=255, verbose_name='Населенный пункт')),
                ('category', models.CharField(choices=[('OPTOM', 'Optom'), ('ROZNITSA', 'Roznitsa'), ('OTHER', 'Other')], default='OPTOM', max_length=128, verbose_name='Подкатегория еды')),
                ('action', models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy')], default='SELL', max_length=128, verbose_name='Действие еды')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('whatsapp', models.BooleanField(verbose_name='Есть Whatsapp')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('settlement', models.CharField(max_length=255, verbose_name='Населенный пункт')),
                ('category', models.CharField(choices=[('WATER', 'Water'), ('ICE', 'Ice'), ('FIREWOOD', 'Firewood'), ('COAL', 'Coal'), ('EARTH', 'Earth'), ('CHERNOZEM', 'Chernozem'), ('MANURE', 'Manure'), ('SEEDLING', 'Seedling')], default='WATER', max_length=128, verbose_name='Подкатегория для дома')),
                ('action', models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy')], default='SELL', max_length=128, verbose_name='Действие для дома')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('whatsapp', models.BooleanField(verbose_name='Есть Whatsapp')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('settlement', models.CharField(max_length=255, verbose_name='Населенный пункт')),
                ('category', models.CharField(choices=[('NEED', 'Need'), ('SEARCH', 'Search'), ('OTHER', 'Other')], default='NEED', max_length=128, verbose_name='Подкатегория еды')),
                ('action', models.CharField(choices=[('PERMANENTLY', 'Permanently'), ('TEMPORALLY', 'Temporally')], default='PERMANENTLY', max_length=128, verbose_name='Действие еды')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('whatsapp', models.BooleanField(verbose_name='Есть Whatsapp')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('settlement', models.CharField(max_length=255, verbose_name='Населенный пункт')),
                ('category', models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('COTTAGE', 'Cottage'), ('AREA', 'Area'), ('FARMLAND', 'Farmlant')], default='HOUSE', max_length=128, verbose_name='Подкатегория недвижимости')),
                ('action', models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy'), ('TRADE', 'Trade'), ('RENT_OUT', 'Rent Out'), ('TO_RENT', 'To Rent')], default='SELL', max_length=128, verbose_name='Действие недвижимости')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('whatsapp', models.BooleanField(verbose_name='Есть Whatsapp')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('settlement', models.CharField(max_length=255, verbose_name='Населенный пункт')),
                ('category', models.CharField(choices=[('BUILDING_REPAIR', 'Building Repair'), ('TRANSPORT', 'Transport'), ('SPEC', 'Spec'), ('PLUMBING', 'Plumbing'), ('ELECTRICY', 'Electricy'), ('AUTOSERVICE', 'Autoservice'), ('HANDYMAN', 'Handyman'), ('OTHER', 'Other')], default='BUILDING_REPAIR', max_length=128, verbose_name='Подкатегория услуги')),
                ('action', models.CharField(choices=[('PROVIDE', 'Provide'), ('USE', 'Use')], default='PROVIDE', max_length=128, verbose_name='Действие услуги')),
            ],
        ),
        migrations.CreateModel(
            name='Uluss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название улуса')),
            ],
            options={
                'verbose_name': 'Улус',
                'verbose_name_plural': 'Улусы',
            },
        ),
    ]
