# Generated by Django 4.1 on 2022-08-09 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertcar',
            old_name='whatsapp',
            new_name='is_whatsapp',
        ),
        migrations.RenameField(
            model_name='advertfood',
            old_name='whatsapp',
            new_name='is_whatsapp',
        ),
        migrations.RenameField(
            model_name='adverthome',
            old_name='whatsapp',
            new_name='is_whatsapp',
        ),
        migrations.RenameField(
            model_name='advertjobs',
            old_name='whatsapp',
            new_name='is_whatsapp',
        ),
        migrations.RenameField(
            model_name='advertrent',
            old_name='whatsapp',
            new_name='is_whatsapp',
        ),
        migrations.RenameField(
            model_name='advertservice',
            old_name='whatsapp',
            new_name='is_whatsapp',
        ),
        migrations.AddField(
            model_name='advertcar',
            name='uluus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advert.uluss', verbose_name='Улус объявления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertfood',
            name='uluus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advert.uluss', verbose_name='Улус объявления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adverthome',
            name='uluus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advert.uluss', verbose_name='Улус объявления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertjobs',
            name='uluus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advert.uluss', verbose_name='Улус объявления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertrent',
            name='uluus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advert.uluss', verbose_name='Улус объявления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertservice',
            name='uluus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advert.uluss', verbose_name='Улус объявления'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ServiceImages/', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advertservice', verbose_name='Объявление')),
            ],
        ),
        migrations.CreateModel(
            name='RentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='RentImages/', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advertrent', verbose_name='Объявление')),
            ],
        ),
        migrations.CreateModel(
            name='JobsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='JobsImages/', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advertjobs', verbose_name='Объявление')),
            ],
        ),
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='HomeImages/', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.adverthome', verbose_name='Объявление')),
            ],
        ),
        migrations.CreateModel(
            name='FoodImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='FoodImages/', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advertfood', verbose_name='Объявление')),
            ],
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CarImages/', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advertcar', verbose_name='Объявление')),
            ],
        ),
    ]
