# Generated by Django 4.1 on 2022-08-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_advertcar_price_advertfood_price_adverthome_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertcar',
            options={'verbose_name': 'Объявление автомобилей', 'verbose_name_plural': 'Объявления автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='advertfood',
            options={'verbose_name': 'Объявление еды', 'verbose_name_plural': 'Объявления еды'},
        ),
        migrations.AlterModelOptions(
            name='adverthome',
            options={'verbose_name': 'Объявление для дома', 'verbose_name_plural': 'Объявления для дома'},
        ),
        migrations.AlterModelOptions(
            name='advertjobs',
            options={'verbose_name': 'Объявление вакансий', 'verbose_name_plural': 'Объявления вакансий'},
        ),
        migrations.AlterModelOptions(
            name='advertrent',
            options={'verbose_name': 'Объявление недвижимости', 'verbose_name_plural': 'Объявления недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='advertservice',
            options={'verbose_name': 'Объявление услуг', 'verbose_name_plural': 'Объявления услуг'},
        ),
        migrations.AlterModelOptions(
            name='carimages',
            options={'verbose_name': 'Изображение автомобилей', 'verbose_name_plural': 'Изображения автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='foodimages',
            options={'verbose_name': 'Изображение еды', 'verbose_name_plural': 'Изображения еды'},
        ),
        migrations.AlterModelOptions(
            name='homeimages',
            options={'verbose_name': 'Изображение для дома', 'verbose_name_plural': 'Изображения для дома'},
        ),
        migrations.AlterModelOptions(
            name='jobsimages',
            options={'verbose_name': 'Изображение вакансий', 'verbose_name_plural': 'Изображения вакансий'},
        ),
        migrations.AlterModelOptions(
            name='rentimages',
            options={'verbose_name': 'Изображение недвижимости', 'verbose_name_plural': 'Изображения недвижимости'},
        ),
        migrations.AlterModelOptions(
            name='serviceimages',
            options={'verbose_name': 'Изображение услуг', 'verbose_name_plural': 'Изображения услуг'},
        ),
    ]
