# Generated by Django 4.1 on 2022-08-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_alter_advertcar_options_alter_advertfood_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertcar',
            name='uluus',
        ),
        migrations.RemoveField(
            model_name='advertfood',
            name='uluus',
        ),
        migrations.RemoveField(
            model_name='adverthome',
            name='uluus',
        ),
        migrations.AlterField(
            model_name='advertjobs',
            name='action',
            field=models.CharField(choices=[('PERMANENTLY', 'Permanently'), ('TEMPORALLY', 'Temporally')], default='PERMANENTLY', max_length=128, verbose_name='Действие вакансии'),
        ),
        migrations.AlterField(
            model_name='advertjobs',
            name='category',
            field=models.CharField(choices=[('NEED', 'Need'), ('SEARCH', 'Search'), ('OTHER', 'Other')], default='NEED', max_length=128, verbose_name='Подкатегория вакансии'),
        ),
        migrations.RemoveField(
            model_name='advertjobs',
            name='uluus',
        ),
        migrations.RemoveField(
            model_name='advertrent',
            name='uluus',
        ),
        migrations.RemoveField(
            model_name='advertservice',
            name='uluus',
        ),
        migrations.AddField(
            model_name='advertcar',
            name='uluus',
            field=models.ManyToManyField(to='advert.uluss', verbose_name='Улус объявления'),
        ),
        migrations.AddField(
            model_name='advertfood',
            name='uluus',
            field=models.ManyToManyField(to='advert.uluss', verbose_name='Улус объявления'),
        ),
        migrations.AddField(
            model_name='adverthome',
            name='uluus',
            field=models.ManyToManyField(to='advert.uluss', verbose_name='Улус объявления'),
        ),
        migrations.AddField(
            model_name='advertjobs',
            name='uluus',
            field=models.ManyToManyField(to='advert.uluss', verbose_name='Улус объявления'),
        ),
        migrations.AddField(
            model_name='advertrent',
            name='uluus',
            field=models.ManyToManyField(to='advert.uluss', verbose_name='Улус объявления'),
        ),
        migrations.AddField(
            model_name='advertservice',
            name='uluus',
            field=models.ManyToManyField(to='advert.uluss', verbose_name='Улус объявления'),
        ),
    ]
