# Generated by Django 4.1 on 2022-08-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_remove_advertcar_uluus_remove_advertfood_uluus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertcar',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отправки объявления'),
        ),
        migrations.AddField(
            model_name='advertfood',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отправки объявления'),
        ),
        migrations.AddField(
            model_name='adverthome',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отправки объявления'),
        ),
        migrations.AddField(
            model_name='advertjobs',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отправки объявления'),
        ),
        migrations.AddField(
            model_name='advertrent',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отправки объявления'),
        ),
        migrations.AddField(
            model_name='advertservice',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время отправки объявления'),
        ),
    ]
