# Generated by Django 4.1 on 2022-08-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_advertcar_date_advertfood_date_adverthome_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertcar',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
        migrations.AddField(
            model_name='advertfood',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
        migrations.AddField(
            model_name='adverthome',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
        migrations.AddField(
            model_name='advertjobs',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
        migrations.AddField(
            model_name='advertrent',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
        migrations.AddField(
            model_name='advertservice',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
    ]
