# Generated by Django 4.1 on 2022-08-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0008_advertcar_slug_advertfood_slug_adverthome_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertcar',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='advertfood',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adverthome',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='advertjobs',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='advertrent',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='advertservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
