# Generated by Django 4.1 on 2022-08-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0009_alter_advertcar_slug_alter_advertfood_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertcar',
            name='category',
            field=models.CharField(choices=[('CAR', 'Car'), ('SPECIAL_CAR', 'Special Car'), ('PARTS', 'Parts'), ('MOTO_TECHNICS', 'Moto Technics'), ('BOATS', 'Boats'), ('OTHER', 'Other')], default='CAR', max_length=128, verbose_name='Подкатегория авто'),
        ),
        migrations.AlterField(
            model_name='adverthome',
            name='category',
            field=models.CharField(choices=[('WATER', 'Water'), ('ICE', 'Ice'), ('FIREWOOD', 'Firewood'), ('COAL', 'Coal'), ('EARTH', 'Earth'), ('CHERNOZEM', 'Chernozem'), ('MANURE', 'Manure'), ('SEEDLING', 'Seedling'), ('OTHER', 'Other')], default='WATER', max_length=128, verbose_name='Подкатегория для дома'),
        ),
        migrations.AlterField(
            model_name='advertrent',
            name='category',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('COTTAGE', 'Cottage'), ('AREA', 'Area'), ('FARMLAND', 'Farmland'), ('OTHER', 'Other')], default='HOUSE', max_length=128, verbose_name='Подкатегория недвижимости'),
        ),
    ]
