# Generated by Django 4.1 on 2022-08-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0013_alter_advertcar_uluus_alter_advertfood_uluus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertRemont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('is_whatsapp', models.BooleanField(verbose_name='Есть Whatsapp')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('settlement', models.CharField(max_length=255, verbose_name='Населенный пункт')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('category', models.CharField(choices=[('DOORS', 'Doors'), ('WINDOWS', 'Windows'), ('PLUMBING', 'Plumbing'), ('MATERIALS', 'Materials'), ('TOOLS', 'Tools'), ('OTHER', 'Other')], default='DOORS', max_length=128, verbose_name='Подкатегория ремонта и строительства')),
                ('action', models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy'), ('TRADE', 'Trade')], default='SELL', max_length=128, verbose_name='Подкатегория ремонта и строительства')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время отправки объявления')),
                ('views', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('uluus', models.ManyToManyField(blank=True, to='advert.uluss', verbose_name='Улус объявления')),
            ],
            options={
                'verbose_name': 'Объявление услуг',
                'verbose_name_plural': 'Объявления услуг',
            },
        ),
        migrations.CreateModel(
            name='RemontImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='JobsImages/', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advertremont', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Изображение ремонта и строительства',
                'verbose_name_plural': 'Изображения ремонта и строительства',
            },
        ),
    ]
