# Generated by Django 4.1 on 2022-08-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0014_advertremont_remontimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertremont',
            options={'verbose_name': 'Объявление ремонта и строительства', 'verbose_name_plural': 'Объявления ремонта и строительства'},
        ),
    ]
