# Generated by Django 4.1 on 2022-08-18 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0017_advertimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertimages',
            name='image',
            field=models.ImageField(upload_to='Images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='advertimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advert', verbose_name='Объявление'),
        ),
    ]
