# Generated by Django 4.1 on 2022-08-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0018_alter_advertimages_image_alter_advertimages_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='category',
        ),
    ]
