# Generated by Django 4.1 on 2022-08-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0019_remove_advert_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='subcategory',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('COTTAGE', 'Cottage'), ('AREA', 'Area'), ('FARMLAND', 'Farmland'), ('CAR', 'Car'), ('SPECIAL_CAR', 'Special Car'), ('PARTS', 'Parts'), ('MOTO_TECHNICS', 'Moto Technics'), ('BOATS', 'Boats'), ('BUILDING_REPAIR', 'Building Repair'), ('TRANSPORT', 'Transport'), ('SPEC', 'Spec'), ('PLUMBING', 'Plumbing'), ('ELECTRICY', 'Electricy'), ('AUTOSERVICE', 'Autoservice'), ('HANDYMAN', 'Handyman'), ('WATER', 'Water'), ('ICE', 'Ice'), ('FIREWOOD', 'Firewood'), ('COAL', 'Coal'), ('EARTH', 'Earth'), ('CHERNOZEM', 'Chernozem'), ('MANURE', 'Manure'), ('SEEDLING', 'Seedling'), ('OPTOM', 'Optom'), ('ROZNITSA', 'Roznitsa'), ('NEED', 'Need'), ('SEARCH', 'Search'), ('DOORS', 'Doors'), ('WINDOWS', 'Windows'), ('MATERIALS', 'Materials'), ('TOOLS', 'Tools'), ('OTHER', 'Other')], max_length=128, verbose_name='Подкатегория объявления'),
        ),
    ]
