# Generated by Django 4.1 on 2022-08-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0020_alter_advert_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='drive_unit',
            field=models.CharField(choices=[('FORWARD', 'Forward'), ('BACK', 'Back'), ('FULL', 'Full')], default=None, max_length=128, null=True, verbose_name='Привод авто'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='improvement',
            field=models.CharField(choices=[('WAS_USED', 'Was Used'), ('BLACK', 'Black'), ('GAS', 'Gas')], default=None, max_length=128, null=True, verbose_name='Благоустройство'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='transmission',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('VARIABLE', 'Variable'), ('MANUAL', 'Manual')], default=None, max_length=128, null=True, verbose_name='Коробка авто'),
        ),
    ]
