# Generated by Django 4.1 on 2022-08-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0021_alter_advert_drive_unit_alter_advert_improvement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='premium_link',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Ссылка на премиум'),
        ),
    ]
