# Generated by Django 4.1 on 2022-08-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0022_advert_premium_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertfood',
            name='uluus',
        ),
        migrations.RemoveField(
            model_name='adverthome',
            name='uluus',
        ),
        migrations.RemoveField(
            model_name='advertjobs',
            name='uluus',
        ),
        migrations.RemoveField(
            model_name='advertremont',
            name='uluus',
        ),
        migrations.RemoveField(
            model_name='advertrent',
            name='uluus',
        ),
        migrations.RemoveField(
            model_name='advertservice',
            name='uluus',
        ),
        migrations.RemoveField(
            model_name='carimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='foodimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='homeimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='jobsimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='remontimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='rentimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='serviceimages',
            name='post',
        ),
        migrations.DeleteModel(
            name='AdvertCar',
        ),
        migrations.DeleteModel(
            name='AdvertFood',
        ),
        migrations.DeleteModel(
            name='AdvertHome',
        ),
        migrations.DeleteModel(
            name='AdvertJobs',
        ),
        migrations.DeleteModel(
            name='AdvertRemont',
        ),
        migrations.DeleteModel(
            name='AdvertRent',
        ),
        migrations.DeleteModel(
            name='AdvertService',
        ),
        migrations.DeleteModel(
            name='CarImages',
        ),
        migrations.DeleteModel(
            name='FoodImages',
        ),
        migrations.DeleteModel(
            name='HomeImages',
        ),
        migrations.DeleteModel(
            name='JobsImages',
        ),
        migrations.DeleteModel(
            name='RemontImages',
        ),
        migrations.DeleteModel(
            name='RentImages',
        ),
        migrations.DeleteModel(
            name='ServiceImages',
        ),
    ]
