# Generated by Django 4.1 on 2022-09-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0025_alter_uluss_capital_alter_uluss_estab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uluss',
            name='capital',
            field=models.CharField(max_length=255, verbose_name='Центр улуса'),
        ),
        migrations.AlterField(
            model_name='uluss',
            name='estab',
            field=models.CharField(max_length=255, verbose_name='Дата образования улуса'),
        ),
        migrations.AlterField(
            model_name='uluss',
            name='image',
            field=models.ImageField(upload_to='uluusImages/', verbose_name='Картинка улуса'),
        ),
        migrations.AlterField(
            model_name='uluss',
            name='population',
            field=models.CharField(max_length=255, verbose_name='Население улуса'),
        ),
        migrations.AlterField(
            model_name='uluss',
            name='square',
            field=models.CharField(max_length=255, verbose_name='Площадь улуса'),
        ),
        migrations.AlterField(
            model_name='uluss',
            name='text',
            field=models.TextField(verbose_name='Описание улуса'),
        ),
    ]
