# The first stage
# Build React static files
FROM node as build

WORKDIR /app/frontend
# COPY ./frontend/package.json /app/frontend
# COPY ./frontend/package-lock.json /app/frontend
COPY ./* /app/frontend
RUN npm install
RUN npm run build

# The second stage
# Copy React static files and start nginx
FROM nginx:1.22-alpine

COPY --from=build /app/frontend/build/ /usr/share/nginx/html


RUN rm /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf