# The first stage
# Build React static files
FROM node as build

WORKDIR /app/frontend
# COPY ./frontend/package.json /app/frontend
# COPY ./frontend/package-lock.json /app/frontend
COPY ./* /app/frontend/
RUN npm install
RUN npm run build

# The second stage
# Copy React static files and start nginx
FROM nginx:1.22-alpine

COPY --from=build /app/frontend/build/ /usr/share/nginx/html
COPY nginx/robots80.txt /
COPY nginx/robots.txt /
COPY nginx/sitemap.xml /

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d